[package]

name = "nordeus-football-analysis"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
chrono = "0.4.38"
reqwest = "0.12.9"
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.132"
sql = "0.4.3"
