version: '3.8'
services:
  db:
    image: postgres:15  
    container_name: football_manager_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: football_manager
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/football_manager
volumes:
  postgres_data:
